package com.tp_cesi.banconet.controller;

import com.tp_cesi.banconet.model.Client;
import com.tp_cesi.banconet.repository.ClientRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/client") // This means URL's start with /demo (after Application path)
public class ClientController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private ClientRepository clientRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewClient (@RequestParam String name
      , @RequestParam String prenom) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Client n = new Client();
    n.setNom(name);
    n.setPrenom(prenom);
    clientRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Client> getAllUsers() {
    // This returns a JSON or XML with the users
    return clientRepository.findAll();
  }
}