package com.tp_cesi.banconet.controller;

import com.tp_cesi.banconet.model.Client;
import com.tp_cesi.banconet.model.CompteCourant;
import com.tp_cesi.banconet.repository.ClientRepository;
import com.tp_cesi.banconet.repository.CompteCourantRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/compteCourant") // This means URL's start with /demo (after Application path)
public class CompteCourantController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private CompteCourantRepository compteCourantRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewCompteCourant(@RequestParam String intitule
      , @RequestParam Double solde, @RequestParam Double montantDecouvertAutorise) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request


    CompteCourant n = new CompteCourant();
n.setIntitule(intitule);
n.setSolde(solde);
n.setMontantDecouvertAutorise(montantDecouvertAutorise);
    compteCourantRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<CompteCourant> getAllUsers() {
    // This returns a JSON or XML with the users
    return compteCourantRepository.findAll();
  }
}